"""pw.x input writer."""

from __future__ import annotations

from typing import Dict, List, Optional, Tuple

from .cell_model import Cell, kpoint_mesh_from_density, sorted_by_species
from .elements import atomic_mass

CALCULATIONS = ("scf", "nscf", "bands", "relax", "vc-relax", "md", "vc-md")

FUNCTIONALS = (
    "POTCAR/UPF default",
    "PBE",
    "PBEsol",
    "revPBE",
    "BLYP",
    "PW91",
    "SCAN",
)

OCCUPATIONS = ("smearing", "fixed", "tetrahedra", "tetrahedra_opt")

SMEARING = ("mv (Marzari-Vanderbilt)", "gaussian", "mp (Methfessel-Paxton)", "fd (Fermi-Dirac)")

VDW_OPTIONS = ("None", "grimme-d2", "grimme-d3", "xdm", "ts-vdw")

DIAGONALIZATION = ("david", "cg", "ppcg", "paro", "rmm-davidson")

KPOINT_MODES = ("Gamma point only", "Automatic mesh", "Automatic (spacing)")

POSITION_UNITS = ("crystal (fractional)", "angstrom")

PSEUDO_PATTERNS = (
    "{El}.UPF",
    "{El}.pbe-n-kjpaw_psl.1.0.0.UPF",
    "{El}_ONCV_PBE-1.0.oncvpsp.upf",
    "{el}_pbe_v1.4.uspp.F.UPF",
)


def default_settings() -> Dict:
    return {
        "title": "Generated by MoleditPy Quantum ESPRESSO Input Generator",
        "calculation": "scf",
        "prefix": "pwscf",
        "outdir": "./out",
        "pseudo_dir": "./pseudo",
        "pseudo_pattern": PSEUDO_PATTERNS[0],
        "functional": FUNCTIONALS[0],
        "ecutwfc": 60.0,
        "ecutrho_auto": True,
        "ecutrho": 480.0,
        "occupations": "smearing",
        "smearing": SMEARING[0],
        "degauss": 0.01,
        "nspin": False,
        "starting_magnetization": 0.5,
        "vdw": VDW_OPTIONS[0],
        "conv_thr": 1e-8,
        "mixing_beta": 0.7,
        "electron_maxstep": 200,
        "diagonalization": "david",
        "nstep": 100,
        "etot_conv_thr": 1e-5,
        "forc_conv_thr": 1e-4,
        "tprnfor": True,
        "tstress": True,
        "press": 0.0,
        "temperature": 300.0,
        "dt": 20.0,
        "kpoint_mode": KPOINT_MODES[1],
        "kmesh": [4, 4, 4],
        "kshift": [0, 0, 0],
        "kspacing": 0.03,
        "position_units": POSITION_UNITS[0],
        "extra_system": "",
        "supercell": [1, 1, 1],
        "padding": 6.0,
        "cubic_box": False,
    }


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------


def _fortran(value) -> str:
    if isinstance(value, bool):
        return ".true." if value else ".false."
    if isinstance(value, float):
        if value != 0 and (abs(value) < 1e-3 or abs(value) >= 1e5):
            return f"{value:.4e}".replace("e", "d")
        return f"{value:g}"
    if isinstance(value, int):
        return str(value)
    return f"'{value}'"


def _namelist(name: str, entries: List[Tuple[str, object]], extra: str = "") -> str:
    lines = [f"&{name}"]
    width = max((len(key) for key, _ in entries), default=1)
    for key, value in entries:
        lines.append(f"  {key:<{width}} = {_fortran(value)}")
    for line in str(extra or "").splitlines():
        if line.strip():
            lines.append(f"  {line.strip()}")
    lines.append("/")
    return "\n".join(lines)


def pseudo_filename(element: str, pattern: str) -> str:
    element = str(element).strip().capitalize()
    return (
        str(pattern)
        .replace("{El}", element)
        .replace("{el}", element.lower())
        .replace("{EL}", element.upper())
    )


def _needs_ions(calculation: str) -> bool:
    return calculation in ("relax", "vc-relax", "md", "vc-md")


def _needs_cell(calculation: str) -> bool:
    return calculation in ("vc-relax", "vc-md")


# --------------------------------------------------------------------------
# sections
# --------------------------------------------------------------------------


def build_control(settings: Dict) -> str:
    calculation = settings.get("calculation", "scf")
    entries: List[Tuple[str, object]] = [
        ("calculation", calculation),
        ("title", str(settings.get("title", "")).replace("\n", " ")),
        ("prefix", settings.get("prefix", "pwscf")),
        ("outdir", settings.get("outdir", "./out")),
        ("pseudo_dir", settings.get("pseudo_dir", "./pseudo")),
        ("verbosity", "high"),
        ("tprnfor", bool(settings.get("tprnfor", True))),
        ("tstress", bool(settings.get("tstress", True))),
    ]
    if _needs_ions(calculation):
        entries.append(("nstep", int(settings.get("nstep", 100))))
        entries.append(("etot_conv_thr", float(settings.get("etot_conv_thr", 1e-5))))
        entries.append(("forc_conv_thr", float(settings.get("forc_conv_thr", 1e-4))))
    if calculation in ("md", "vc-md"):
        entries.append(("dt", float(settings.get("dt", 20.0))))
    return _namelist("CONTROL", entries)


def build_system(cell: Cell, settings: Dict) -> str:
    _, counts = sorted_by_species(cell)
    entries: List[Tuple[str, object]] = [
        ("ibrav", 0),
        ("nat", len(cell.atoms)),
        ("ntyp", len(counts)),
        ("ecutwfc", float(settings.get("ecutwfc", 60.0))),
    ]

    ecutwfc = float(settings.get("ecutwfc", 60.0))
    ecutrho = ecutwfc * 8.0 if settings.get("ecutrho_auto", True) else float(settings.get("ecutrho", 480.0))
    entries.append(("ecutrho", ecutrho))

    occupations = settings.get("occupations", "smearing")
    entries.append(("occupations", occupations))
    if occupations == "smearing":
        entries.append(("smearing", str(settings.get("smearing", SMEARING[0])).split()[0]))
        entries.append(("degauss", float(settings.get("degauss", 0.01))))

    functional = settings.get("functional", FUNCTIONALS[0])
    if functional != FUNCTIONALS[0]:
        entries.append(("input_dft", functional))

    vdw = settings.get("vdw", "None")
    if vdw and vdw != "None":
        entries.append(("vdw_corr", vdw))

    if settings.get("nspin"):
        entries.append(("nspin", 2))
        magnetization = float(settings.get("starting_magnetization", 0.5))
        for index in range(len(counts)):
            entries.append((f"starting_magnetization({index + 1})", magnetization))

    return _namelist("SYSTEM", entries, settings.get("extra_system", ""))


def build_electrons(settings: Dict) -> str:
    return _namelist(
        "ELECTRONS",
        [
            ("conv_thr", float(settings.get("conv_thr", 1e-8))),
            ("mixing_beta", float(settings.get("mixing_beta", 0.7))),
            ("electron_maxstep", int(settings.get("electron_maxstep", 200))),
            ("diagonalization", settings.get("diagonalization", "david")),
        ],
    )


def build_ions(settings: Dict) -> str:
    calculation = settings.get("calculation", "scf")
    if not _needs_ions(calculation):
        return ""
    if calculation in ("md", "vc-md"):
        entries = [
            ("ion_dynamics", "verlet"),
            ("ion_temperature", "rescaling"),
            ("tempw", float(settings.get("temperature", 300.0))),
        ]
    else:
        entries = [("ion_dynamics", "bfgs")]
    return _namelist("IONS", entries)


def build_cell_namelist(settings: Dict) -> str:
    if not _needs_cell(settings.get("calculation", "scf")):
        return ""
    return _namelist(
        "CELL",
        [
            ("cell_dynamics", "bfgs" if settings.get("calculation") == "vc-relax" else "pr"),
            ("press", float(settings.get("press", 0.0))),
            ("press_conv_thr", 0.5),
        ],
    )


def build_atomic_species(cell: Cell, settings: Dict) -> str:
    _, counts = sorted_by_species(cell)
    pattern = settings.get("pseudo_pattern", PSEUDO_PATTERNS[0])
    lines = ["ATOMIC_SPECIES"]
    for element, _ in counts:
        lines.append(
            f"  {element:<3} {atomic_mass(element):>10.4f}  {pseudo_filename(element, pattern)}"
        )
    return "\n".join(lines)


def build_cell_parameters(cell: Cell) -> str:
    lines = ["CELL_PARAMETERS angstrom"]
    for vector in cell.lattice:
        lines.append("  {: >16.10f} {: >16.10f} {: >16.10f}".format(*[float(v) for v in vector]))
    return "\n".join(lines)


def build_atomic_positions(cell: Cell, settings: Dict) -> str:
    crystal = settings.get("position_units", POSITION_UNITS[0]).startswith("crystal")
    lines = ["ATOMIC_POSITIONS " + ("crystal" if crystal else "angstrom")]
    atoms, _ = sorted_by_species(cell)
    for atom in atoms:
        values = atom.fract if crystal else atom.cart
        lines.append(
            "  {:<3} {: >16.10f} {: >16.10f} {: >16.10f}".format(
                atom.element, *[float(v) for v in values]
            )
        )
    return "\n".join(lines)


def build_kpoints(cell: Cell, settings: Dict) -> str:
    mode = settings.get("kpoint_mode", KPOINT_MODES[1])
    if mode == "Gamma point only":
        return "K_POINTS gamma"
    if mode == "Automatic (spacing)":
        mesh = kpoint_mesh_from_density(cell, float(settings.get("kspacing", 0.03)))
        shift = (0, 0, 0)
    else:
        mesh = tuple(max(1, int(value)) for value in settings.get("kmesh", [4, 4, 4]))
        shift = tuple(1 if int(value) else 0 for value in settings.get("kshift", [0, 0, 0]))
    return (
        "K_POINTS automatic\n"
        f"  {mesh[0]:d} {mesh[1]:d} {mesh[2]:d}  {shift[0]:d} {shift[1]:d} {shift[2]:d}"
    )


# --------------------------------------------------------------------------
# assembly
# --------------------------------------------------------------------------


def build_input(cell: Cell, settings: Optional[Dict] = None) -> str:
    settings = {**default_settings(), **(settings or {})}
    blocks = [
        build_control(settings),
        build_system(cell, settings),
        build_electrons(settings),
        build_ions(settings),
        build_cell_namelist(settings),
        build_atomic_species(cell, settings),
        build_cell_parameters(cell),
        build_atomic_positions(cell, settings),
        build_kpoints(cell, settings),
    ]
    return "\n\n".join(block for block in blocks if block) + "\n"


def build_preview(cell: Cell, settings: Optional[Dict] = None) -> str:
    return build_input(cell, settings)


def suggested_filename(settings: Optional[Dict] = None) -> str:
    settings = {**default_settings(), **(settings or {})}
    prefix = str(settings.get("prefix") or "pwscf").strip() or "pwscf"
    return f"{prefix}.{settings.get('calculation', 'scf')}.in"
